language: python
os: linux
python:
  - "3.7"
  - "3.6"

# install required dependencies
install:
  - pip install -r ./requirements/requirement-pyhton3.7.txt

jobs:
  include:
    - name: test wiht python 3.6
      python: 3.6
      stage: test
    - name: test with python 3.7
      python: 3.7
      stage: test

# run the build script
script:
  - pytest

# install packages before running
before_install:
  - echo "Before install"
  - sudo apt-get update
after_script:
  - echo "After script installation"

deploy:
  - skip_cleanup: true
after_deploy:
  - echo "After deploy"
